
#include "cpu_instructions.h"
#include "cpu.h"


static void nop(struct Cpu *cpu)
{
    (void)cpu;
}


const struct Instruction instructions[256] = {
    // 0x00
    { "NOP",             0, nop },
    { "LD BC, 0x%04x",   2, NULL },
    { "LD (BC), A",      0, NULL },
    { "INC BC",          0, NULL },
    { "INC B",           0, NULL },
    { "DEC B",           0, NULL },
    { "LD B, 0x%02x",    1, NULL },
    { "RLCA",            0, NULL },
    { "LD (0x%04x), SP", 2, NULL },
    { "ADD HL, BC",      0, NULL },
    { "LD A, (BC)",      0, NULL },
    { "DEC BC",          0, NULL },
    { "INC C",           0, NULL },
    { "DEC C",           0, NULL },
    { "LD C, 0x%02x",    1, NULL },
    { "RRCA",            0, NULL },

    // 0x10
    { "STOP %d",         1, NULL },
    { "LD DE, 0x%04x",   2, NULL },
    { "LD (DE), A",      0, NULL },
    { "INC DE",          0, NULL },
    { "INC D",           0, NULL },
    { "DEC D",           0, NULL },
    { "LD D, 0x%02x",    1, NULL },
    { "RLA",             0, NULL },
    { "JR %d",           1, NULL },
    { "ADD HL, DE",      0, NULL },
    { "LD A, (DE)",      0, NULL },
    { "DEC DE",          0, NULL },
    { "INC E",           0, NULL },
    { "DEC E",           0, NULL },
    { "LD E, 0x%02x",    1, NULL },
    { "RRA",             0, NULL },

    // 0x20
    { "JR NZ, %d",       1, NULL },
    { "LD HL, 0x%04x",   2, NULL },
    { "LD (HL+), A",     0, NULL },
    { "INC HL",          0, NULL },
    { "INC H",           0, NULL },
    { "DEC H",           0, NULL },
    { "LD H, 0x%02x",    1, NULL },
    { "DAA",             0, NULL },
    { "JR Z, %d",        1, NULL },
    { "ADD HL, HL",      0, NULL },
    { "LD A, (HL+)",     0, NULL },
    { "DEC HL",          0, NULL },
    { "INC L",           0, NULL },
    { "DEC L",           0, NULL },
    { "LD L, 0x%02x",    1, NULL },
    { "CPL",             0, NULL },

    // 0x30
    { "JR NC, %d",       1, NULL },
    { "LD SP, 0x%04x",   2, NULL },
    { "LD (HL-), A",     0, NULL },
    { "INC SP",          0, NULL },
    { "INC (HL)",        0, NULL },
    { "DEC (HL)",        0, NULL },
    { "LD (HL), 0x%02x", 1, NULL },
    { "SCF",             0, NULL },
    { "JR C, %d",        1, NULL },
    { "ADD HL, SP",      0, NULL },
    { "LD A, (HL-)",     0, NULL },
    { "DEC SP",          0, NULL },
    { "INC A",           0, NULL },
    { "DEC A",           0, NULL },
    { "LD A, 0x%02x",    1, NULL },
    { "CCF",             0, NULL },

    // 0x40
    { "LD B, B",         0, NULL },
    { "LD B, C",         0, NULL },
    { "LD B, D",         0, NULL },
    { "LD B, E",         0, NULL },
    { "LD B, H",         0, NULL },
    { "LD B, L",         0, NULL },
    { "LD B, (HL)",      0, NULL },
    { "LD B, A",         0, NULL },
    { "LD C, B",         0, NULL },
    { "LD C, C",         0, NULL },
    { "LD C, D",         0, NULL },
    { "LD C, E",         0, NULL },
    { "LD C, H",         0, NULL },
    { "LD C, L",         0, NULL },
    { "LD C, (HL)",      0, NULL },
    { "LD C, A",         0, NULL },

    // 0x50
    { "LD D, B",         0, NULL },
    { "LD D, C",         0, NULL },
    { "LD D, D",         0, NULL },
    { "LD D, E",         0, NULL },
    { "LD D, H",         0, NULL },
    { "LD D, L",         0, NULL },
    { "LD D, (HL)",      0, NULL },
    { "LD D, A",         0, NULL },
    { "LD E, B",         0, NULL },
    { "LD E, C",         0, NULL },
    { "LD E, D",         0, NULL },
    { "LD E, E",         0, NULL },
    { "LD E, H",         0, NULL },
    { "LD E, L",         0, NULL },
    { "LD E, (HL)",      0, NULL },
    { "LD E, A",         0, NULL },

    // 0x60
    { "LD H, B",         0, NULL },
    { "LD H, C",         0, NULL },
    { "LD H, D",         0, NULL },
    { "LD H, E",         0, NULL },
    { "LD H, H",         0, NULL },
    { "LD H, L",         0, NULL },
    { "LD H, (HL)",      0, NULL },
    { "LD H, A",         0, NULL },
    { "LD L, B",         0, NULL },
    { "LD L, C",         0, NULL },
    { "LD L, D",         0, NULL },
    { "LD L, E",         0, NULL },
    { "LD L, H",         0, NULL },
    { "LD L, L",         0, NULL },
    { "LD L, (HL)",      0, NULL },
    { "LD L, A",         0, NULL },

    // 0x70
    { "LD (HL), B",      0, NULL },
    { "LD (HL), C",      0, NULL },
    { "LD (HL), D",      0, NULL },
    { "LD (HL), E",      0, NULL },
    { "LD (HL), H",      0, NULL },
    { "LD (HL), L",      0, NULL },
    { "HALT",            0, NULL },
    { "LD (HL), A",      0, NULL },
    { "LD A, B",         0, NULL },
    { "LD A, C",         0, NULL },
    { "LD A, D",         0, NULL },
    { "LD A, E",         0, NULL },
    { "LD A, H",         0, NULL },
    { "LD A, L",         0, NULL },
    { "LD A, (HL)",      0, NULL },
    { "LD A, A",         0, NULL },

    // 0x80
    { "ADD A, B",        0, NULL },
    { "ADD A, C",        0, NULL },
    { "ADD A, D",        0, NULL },
    { "ADD A, E",        0, NULL },
    { "ADD A, H",        0, NULL },
    { "ADD A, L",        0, NULL },
    { "ADD A, (HL)",     0, NULL },
    { "ADD A, A",        0, NULL },
    { "ADC A, B",        0, NULL },
    { "ADC A, C",        0, NULL },
    { "ADC A, D",        0, NULL },
    { "ADC A, E",        0, NULL },
    { "ADC A, H",        0, NULL },
    { "ADC A, L",        0, NULL },
    { "ADC A, (HL)",     0, NULL },
    { "ADC A, A",        0, NULL },

    // 0x90
    { "SUB B",           0, NULL },
    { "SUB C",           0, NULL },
    { "SUB D",           0, NULL },
    { "SUB E",           0, NULL },
    { "SUB H",           0, NULL },
    { "SUB L",           0, NULL },
    { "SUB (HL)",        0, NULL },
    { "SUB A",           0, NULL },
    { "SBC A, B",        0, NULL },
    { "SBC A, C",        0, NULL },
    { "SBC A, D",        0, NULL },
    { "SBC A, E",        0, NULL },
    { "SBC A, H",        0, NULL },
    { "SBC A, L",        0, NULL },
    { "SBC A, (HL)",     0, NULL },
    { "SBC A, A",        0, NULL },

    // 0xa0
    { "AND B",           0, NULL },
    { "AND C",           0, NULL },
    { "AND D",           0, NULL },
    { "AND E",           0, NULL },
    { "AND H",           0, NULL },
    { "AND L",           0, NULL },
    { "AND (HL)",        0, NULL },
    { "AND A",           0, NULL },
    { "XOR B",           0, NULL },
    { "XOR C",           0, NULL },
    { "XOR D",           0, NULL },
    { "XOR E",           0, NULL },
    { "XOR H",           0, NULL },
    { "XOR L",           0, NULL },
    { "XOR (HL)",        0, NULL },
    { "XOR A",           0, NULL },

    // 0xb0
    { "OR B",            0, NULL },
    { "OR C",            0, NULL },
    { "OR D",            0, NULL },
    { "OR E",            0, NULL },
    { "OR H",            0, NULL },
    { "OR L",            0, NULL },
    { "OR (HL)",         0, NULL },
    { "OR A",            0, NULL },
    { "CP B",            0, NULL },
    { "CP C",            0, NULL },
    { "CP D",            0, NULL },
    { "CP E",            0, NULL },
    { "CP H",            0, NULL },
    { "CP L",            0, NULL },
    { "CP (HL)",         0, NULL },
    { "CP A",            0, NULL },

    // 0xc0
    { "RET NZ",          0, NULL },
    { "POP BC",          0, NULL },
    { "JP NZ, 0x%04x",   2, NULL },
    { "JP 0x%04x",       2, NULL },
    { "CALL NZ, 0x%04x", 2, NULL },
    { "PUSH BC",         0, NULL },
    { "ADD A, 0x%02x",   1, NULL },
    { "RST 0x00",        0, NULL },
    { "RET Z",           0, NULL },
    { "RET",             0, NULL },
    { "JP Z, 0x%04x",    2, NULL },
    { "<prefix cb>",     0, NULL },
    { "CALL Z, 0x%04x",  0, NULL },
    { "CALL 0x%04x",     0, NULL },
    { "ADC A, 0x%02x",   0, NULL },
    { "RST 0x08",        0, NULL },

    // 0xd0
    { "RET NC",          0, NULL },
    { "POP DE",          0, NULL },
    { "JP NC, 0x%04x",   2, NULL },
    { "<undocumented>",  0, NULL },
    { "CALL NC, 0x%04x", 2, NULL },
    { "PUSH DE",         0, NULL },
    { "SUB 0x%02x",      1, NULL },
    { "RST 0x10",        0, NULL },
    { "RET C",           0, NULL },
    { "RETI",            0, NULL },
    { "JP C, 0x%04x",    2, NULL },
    { "<undocumented>",  0, NULL },
    { "CALL C, 0x%04x",  0, NULL },
    { "<undocumented>",  0, NULL },
    { "SBC A, 0x%02x",   0, NULL },
    { "RST 0x18",        0, NULL },

    // 0xe0
    { "LDH (0x%02x), A", 0, NULL },
    { "POP HL",          0, NULL },
    { "LD (C), A",       0, NULL },
    { "<undocumented>",  0, NULL },
    { "<undocumented>",  0, NULL },
    { "PUSH HL",         0, NULL },
    { "AND 0x%02x",      1, NULL },
    { "RST 0x20",        0, NULL },
    { "ADD SP, %d",      1, NULL },
    { "JP (HL)",         0, NULL },
    { "LD (0x%04x), A",  2, NULL },
    { "<undocumented>",  0, NULL },
    { "<undocumented>",  0, NULL },
    { "<undocumented>",  0, NULL },
    { "XOR A, 0x%02x",   0, NULL },
    { "RST 0x28",        0, NULL },

    // 0xf0
    { "LDH A, (0x%02x)", 0, NULL },
    { "POP AF",          0, NULL },
    { "LD A, (C)",       0, NULL },
    { "DI",              0, NULL },
    { "<undocumented>",  0, NULL },
    { "PUSH AF",         0, NULL },
    { "OR 0x%02x",       1, NULL },
    { "RST 0x30",        0, NULL },
    { "LD HL, SP%+d",    1, NULL },
    { "LD SP, HL",       0, NULL },
    { "LD A, (0x%04x)",  2, NULL },
    { "EI",              0, NULL },
    { "<undocumented>",  0, NULL },
    { "<undocumented>",  0, NULL },
    { "CP A, 0x%02x",    0, NULL },
    { "RST 0x38",        0, NULL },
};


const struct Instruction cbInstructions[256] = {
    // 0x00
    { "RLC B",      0, NULL },
    { "RLC C",      0, NULL },
    { "RLC D",      0, NULL },
    { "RLC E",      0, NULL },
    { "RLC H",      0, NULL },
    { "RLC L",      0, NULL },
    { "RLC (HL)",   0, NULL },
    { "RLC A",      0, NULL },
    { "RRC B",      0, NULL },
    { "RRC C",      0, NULL },
    { "RRC D",      0, NULL },
    { "RRC E",      0, NULL },
    { "RRC H",      0, NULL },
    { "RRC L",      0, NULL },
    { "RRC (HL)",   0, NULL },
    { "RRC A",      0, NULL },

    // 0x10
    { "RL B",       0, NULL },
    { "RL C",       0, NULL },
    { "RL D",       0, NULL },
    { "RL E",       0, NULL },
    { "RL H",       0, NULL },
    { "RL L",       0, NULL },
    { "RL (HL)",    0, NULL },
    { "RL A",       0, NULL },
    { "RR B",       0, NULL },
    { "RR C",       0, NULL },
    { "RR D",       0, NULL },
    { "RR E",       0, NULL },
    { "RR H",       0, NULL },
    { "RR L",       0, NULL },
    { "RR (HL)",    0, NULL },
    { "RR A",       0, NULL },

    // 0x20
    { "SLA B",      0, NULL },
    { "SLA C",      0, NULL },
    { "SLA D",      0, NULL },
    { "SLA E",      0, NULL },
    { "SLA H",      0, NULL },
    { "SLA L",      0, NULL },
    { "SLA (HL)",   0, NULL },
    { "SLA A",      0, NULL },
    { "SRA B",      0, NULL },
    { "SRA C",      0, NULL },
    { "SRA D",      0, NULL },
    { "SRA E",      0, NULL },
    { "SRA H",      0, NULL },
    { "SRA L",      0, NULL },
    { "SRA (HL)",   0, NULL },
    { "SRA A",      0, NULL },

    // 0x30
    { "SWAP B",     0, NULL },
    { "SWAP C",     0, NULL },
    { "SWAP D",     0, NULL },
    { "SWAP E",     0, NULL },
    { "SWAP H",     0, NULL },
    { "SWAP L",     0, NULL },
    { "SWAP (HL)",  0, NULL },
    { "SWAP A",     0, NULL },
    { "SRL B",      0, NULL },
    { "SRL C",      0, NULL },
    { "SRL D",      0, NULL },
    { "SRL E",      0, NULL },
    { "SRL H",      0, NULL },
    { "SRL L",      0, NULL },
    { "SRL (HL)",   0, NULL },
    { "SRL A",      0, NULL },

    // 0x40
    { "BIT 0 B",      0, NULL },
    { "BIT 0 C",      0, NULL },
    { "BIT 0 D",      0, NULL },
    { "BIT 0 E",      0, NULL },
    { "BIT 0 H",      0, NULL },
    { "BIT 0 L",      0, NULL },
    { "BIT 0 (HL)",   0, NULL },
    { "BIT 0 A",      0, NULL },
    { "BIT 1 B",      0, NULL },
    { "BIT 1 C",      0, NULL },
    { "BIT 1 D",      0, NULL },
    { "BIT 1 E",      0, NULL },
    { "BIT 1 H",      0, NULL },
    { "BIT 1 L",      0, NULL },
    { "BIT 1 (HL)",   0, NULL },
    { "BIT 1 A",      0, NULL },

    // 0x50
    { "BIT 2 B",      0, NULL },
    { "BIT 2 C",      0, NULL },
    { "BIT 2 D",      0, NULL },
    { "BIT 2 E",      0, NULL },
    { "BIT 2 H",      0, NULL },
    { "BIT 2 L",      0, NULL },
    { "BIT 2 (HL)",   0, NULL },
    { "BIT 2 A",      0, NULL },
    { "BIT 3 B",      0, NULL },
    { "BIT 3 C",      0, NULL },
    { "BIT 3 D",      0, NULL },
    { "BIT 3 E",      0, NULL },
    { "BIT 3 H",      0, NULL },
    { "BIT 3 L",      0, NULL },
    { "BIT 3 (HL)",   0, NULL },
    { "BIT 3 A",      0, NULL },

    // 0x60
    { "BIT 4 B",      0, NULL },
    { "BIT 4 C",      0, NULL },
    { "BIT 4 D",      0, NULL },
    { "BIT 4 E",      0, NULL },
    { "BIT 4 H",      0, NULL },
    { "BIT 4 L",      0, NULL },
    { "BIT 4 (HL)",   0, NULL },
    { "BIT 4 A",      0, NULL },
    { "BIT 5 B",      0, NULL },
    { "BIT 5 C",      0, NULL },
    { "BIT 5 D",      0, NULL },
    { "BIT 5 E",      0, NULL },
    { "BIT 5 H",      0, NULL },
    { "BIT 5 L",      0, NULL },
    { "BIT 5 (HL)",   0, NULL },
    { "BIT 5 A",      0, NULL },

    // 0x70
    { "BIT 6 B",      0, NULL },
    { "BIT 6 C",      0, NULL },
    { "BIT 6 D",      0, NULL },
    { "BIT 6 E",      0, NULL },
    { "BIT 6 H",      0, NULL },
    { "BIT 6 L",      0, NULL },
    { "BIT 6 (HL)",   0, NULL },
    { "BIT 6 A",      0, NULL },
    { "BIT 7 B",      0, NULL },
    { "BIT 7 C",      0, NULL },
    { "BIT 7 D",      0, NULL },
    { "BIT 7 E",      0, NULL },
    { "BIT 7 H",      0, NULL },
    { "BIT 7 L",      0, NULL },
    { "BIT 7 (HL)",   0, NULL },
    { "BIT 7 A",      0, NULL },

    // 0x80
    { "RES 0 B",      0, NULL },
    { "RES 0 C",      0, NULL },
    { "RES 0 D",      0, NULL },
    { "RES 0 E",      0, NULL },
    { "RES 0 H",      0, NULL },
    { "RES 0 L",      0, NULL },
    { "RES 0 (HL)",   0, NULL },
    { "RES 0 A",      0, NULL },
    { "RES 1 B",      0, NULL },
    { "RES 1 C",      0, NULL },
    { "RES 1 D",      0, NULL },
    { "RES 1 E",      0, NULL },
    { "RES 1 H",      0, NULL },
    { "RES 1 L",      0, NULL },
    { "RES 1 (HL)",   0, NULL },
    { "RES 1 A",      0, NULL },

    // 0x90
    { "RES 2 B",      0, NULL },
    { "RES 2 C",      0, NULL },
    { "RES 2 D",      0, NULL },
    { "RES 2 E",      0, NULL },
    { "RES 2 H",      0, NULL },
    { "RES 2 L",      0, NULL },
    { "RES 2 (HL)",   0, NULL },
    { "RES 2 A",      0, NULL },
    { "RES 3 B",      0, NULL },
    { "RES 3 C",      0, NULL },
    { "RES 3 D",      0, NULL },
    { "RES 3 E",      0, NULL },
    { "RES 3 H",      0, NULL },
    { "RES 3 L",      0, NULL },
    { "RES 3 (HL)",   0, NULL },
    { "RES 3 A",      0, NULL },

    // 0xa0
    { "RES 4 B",      0, NULL },
    { "RES 4 C",      0, NULL },
    { "RES 4 D",      0, NULL },
    { "RES 4 E",      0, NULL },
    { "RES 4 H",      0, NULL },
    { "RES 4 L",      0, NULL },
    { "RES 4 (HL)",   0, NULL },
    { "RES 4 A",      0, NULL },
    { "RES 5 B",      0, NULL },
    { "RES 5 C",      0, NULL },
    { "RES 5 D",      0, NULL },
    { "RES 5 E",      0, NULL },
    { "RES 5 H",      0, NULL },
    { "RES 5 L",      0, NULL },
    { "RES 5 (HL)",   0, NULL },
    { "RES 5 A",      0, NULL },

    // 0xb0
    { "RES 6 B",      0, NULL },
    { "RES 6 C",      0, NULL },
    { "RES 6 D",      0, NULL },
    { "RES 6 E",      0, NULL },
    { "RES 6 H",      0, NULL },
    { "RES 6 L",      0, NULL },
    { "RES 6 (HL)",   0, NULL },
    { "RES 6 A",      0, NULL },
    { "RES 7 B",      0, NULL },
    { "RES 7 C",      0, NULL },
    { "RES 7 D",      0, NULL },
    { "RES 7 E",      0, NULL },
    { "RES 7 H",      0, NULL },
    { "RES 7 L",      0, NULL },
    { "RES 7 (HL)",   0, NULL },
    { "RES 7 A",      0, NULL },

    // 0xc0
    { "SET 0 B",      0, NULL },
    { "SET 0 C",      0, NULL },
    { "SET 0 D",      0, NULL },
    { "SET 0 E",      0, NULL },
    { "SET 0 H",      0, NULL },
    { "SET 0 L",      0, NULL },
    { "SET 0 (HL)",   0, NULL },
    { "SET 0 A",      0, NULL },
    { "SET 1 B",      0, NULL },
    { "SET 1 C",      0, NULL },
    { "SET 1 D",      0, NULL },
    { "SET 1 E",      0, NULL },
    { "SET 1 H",      0, NULL },
    { "SET 1 L",      0, NULL },
    { "SET 1 (HL)",   0, NULL },
    { "SET 1 A",      0, NULL },

    // 0xd0
    { "SET 2 B",      0, NULL },
    { "SET 2 C",      0, NULL },
    { "SET 2 D",      0, NULL },
    { "SET 2 E",      0, NULL },
    { "SET 2 H",      0, NULL },
    { "SET 2 L",      0, NULL },
    { "SET 2 (HL)",   0, NULL },
    { "SET 2 A",      0, NULL },
    { "SET 3 B",      0, NULL },
    { "SET 3 C",      0, NULL },
    { "SET 3 D",      0, NULL },
    { "SET 3 E",      0, NULL },
    { "SET 3 H",      0, NULL },
    { "SET 3 L",      0, NULL },
    { "SET 3 (HL)",   0, NULL },
    { "SET 3 A",      0, NULL },

    // 0xe0
    { "SET 4 B",      0, NULL },
    { "SET 4 C",      0, NULL },
    { "SET 4 D",      0, NULL },
    { "SET 4 E",      0, NULL },
    { "SET 4 H",      0, NULL },
    { "SET 4 L",      0, NULL },
    { "SET 4 (HL)",   0, NULL },
    { "SET 4 A",      0, NULL },
    { "SET 5 B",      0, NULL },
    { "SET 5 C",      0, NULL },
    { "SET 5 D",      0, NULL },
    { "SET 5 E",      0, NULL },
    { "SET 5 H",      0, NULL },
    { "SET 5 L",      0, NULL },
    { "SET 5 (HL)",   0, NULL },
    { "SET 5 A",      0, NULL },

    // 0xf0
    { "SET 6 B",      0, NULL },
    { "SET 6 C",      0, NULL },
    { "SET 6 D",      0, NULL },
    { "SET 6 E",      0, NULL },
    { "SET 6 H",      0, NULL },
    { "SET 6 L",      0, NULL },
    { "SET 6 (HL)",   0, NULL },
    { "SET 6 A",      0, NULL },
    { "SET 7 B",      0, NULL },
    { "SET 7 C",      0, NULL },
    { "SET 7 D",      0, NULL },
    { "SET 7 E",      0, NULL },
    { "SET 7 H",      0, NULL },
    { "SET 7 L",      0, NULL },
    { "SET 7 (HL)",   0, NULL },
    { "SET 7 A",      0, NULL },
};
